[package]
name = "bnfgen-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bnfgen = { workspace = true }
clap = { version = "4.5.59", features = ["derive"] }
miette = { workspace = true, features = ["fancy"] }
rand = { workspace = true }
